"""
═══════════════════════════════════════════════════════════════
VendorIQ — SQLAlchemy ORM Models
All database tables for the vendor risk intelligence platform
═══════════════════════════════════════════════════════════════
"""

from datetime import datetime
from sqlalchemy import (
    Column, Integer, Float, String, Text, DateTime, ForeignKey, JSON
)
from sqlalchemy.orm import relationship
from database import Base


class Vendor(Base):
    """
    Core vendor table — stores all 5,000 vendors with their
    operational KPIs, financial metrics, and computed risk scores.
    """
    __tablename__ = "vendors"

    vendor_id = Column(String(20), primary_key=True, index=True)
    vendor_name = Column(String(200), nullable=False)
    country = Column(String(100))
    region = Column(String(100))
    category = Column(String(100))
    tier = Column(String(10))
    contract_value = Column(String(50))
    lat = Column(Float)
    lng = Column(Float)

    # ── Operational KPIs ─────────────────────────────────────
    ontime_delivery = Column(Float, default=0)
    avg_lead_time = Column(Float, default=0)
    lead_time_variability = Column(Float, default=0)
    emergency_fulfillment = Column(Float, default=0)
    avg_days_late = Column(Float, default=0)
    shipment_accuracy = Column(Float, default=0)

    # ── Quality KPIs ─────────────────────────────────────────
    defect_rate_ppm = Column(Float, default=0)
    field_failure_rate = Column(Float, default=0)
    warranty_claims = Column(Float, default=0)
    inspection_pass_rate = Column(Float, default=0)
    certification_score = Column(Float, default=0)

    # ── Financial KPIs ───────────────────────────────────────
    financial_stability = Column(Float, default=0)
    revenue_trend = Column(Float, default=0)
    debt_equity = Column(Float, default=0)
    dpo = Column(Float, default=0)

    # ── Logistics KPIs ───────────────────────────────────────
    carrier_dependency = Column(Float, default=0)

    # ── Geopolitical KPIs ────────────────────────────────────
    gpr_score = Column(Float, default=0)
    tariff_exposure = Column(Float, default=0)
    disaster_risk = Column(Float, default=0)
    single_source = Column(Float, default=0)
    tier2_visibility = Column(Float, default=0)

    # ── ESG & Compliance ─────────────────────────────────────
    audit_score = Column(Float, default=0)
    capacity_utilization = Column(Float, default=0)
    carbon_score = Column(Float, default=0)
    labor_compliance = Column(Float, default=0)
    esg_score = Column(Float, default=0)
    vendor_tenure = Column(Float, default=0)
    response_time = Column(Float, default=0)

    # ── Computed Risk Fields ─────────────────────────────────
    final_risk_score = Column(Float, default=0)
    risk_category = Column(String(20), default="Low")

    created_at = Column(DateTime, default=datetime.utcnow)

    # ── Relationships ────────────────────────────────────────
    risk_history = relationship("RiskHistory", back_populates="vendor", cascade="all, delete-orphan")
    alerts = relationship("Alert", back_populates="vendor", cascade="all, delete-orphan")
    event_impacts = relationship("EventImpact", back_populates="vendor", cascade="all, delete-orphan")


class LiveEvent(Base):
    """
    Stores live disruption events fetched from NewsAPI
    or manually injected via the simulation engine.
    """
    __tablename__ = "live_events"

    event_id = Column(Integer, primary_key=True, autoincrement=True)
    event_title = Column(String(500), nullable=False)
    event_type = Column(String(100))       # War, Maritime, Trade, etc.
    event_description = Column(Text)
    event_severity = Column(String(20))    # critical, high, moderate, low
    affected_region = Column(String(100))
    source_url = Column(String(500))
    is_active = Column(Integer, default=1)  # 1=active, 0=resolved
    created_at = Column(DateTime, default=datetime.utcnow)

    # ── Relationships ────────────────────────────────────────
    impacts = relationship("EventImpact", back_populates="event", cascade="all, delete-orphan")


class RiskHistory(Base):
    """
    Tracks every risk score change for audit trail and analytics.
    """
    __tablename__ = "risk_history"

    history_id = Column(Integer, primary_key=True, autoincrement=True)
    vendor_id = Column(String(20), ForeignKey("vendors.vendor_id"), nullable=False)
    previous_risk_score = Column(Float)
    updated_risk_score = Column(Float)
    trigger_reason = Column(String(500))
    timestamp = Column(DateTime, default=datetime.utcnow)

    vendor = relationship("Vendor", back_populates="risk_history")


class Alert(Base):
    """
    Dynamic alerts generated by the risk engine and event engine.
    """
    __tablename__ = "alerts"

    alert_id = Column(Integer, primary_key=True, autoincrement=True)
    vendor_id = Column(String(20), ForeignKey("vendors.vendor_id"), nullable=True)
    alert_type = Column(String(100))       # Risk Threshold, Disruption, etc.
    alert_message = Column(Text)
    severity = Column(String(20))          # critical, high, moderate, low
    is_read = Column(Integer, default=0)
    created_at = Column(DateTime, default=datetime.utcnow)

    vendor = relationship("Vendor", back_populates="alerts")


class EventImpact(Base):
    """
    Maps live events to specific vendor KPI impacts.
    Records which parameter was changed and by how much.
    """
    __tablename__ = "event_impacts"

    impact_id = Column(Integer, primary_key=True, autoincrement=True)
    event_id = Column(Integer, ForeignKey("live_events.event_id"), nullable=False)
    vendor_id = Column(String(20), ForeignKey("vendors.vendor_id"), nullable=False)
    impacted_parameter = Column(String(100))
    impact_value = Column(Float)
    created_at = Column(DateTime, default=datetime.utcnow)

    event = relationship("LiveEvent", back_populates="impacts")
    vendor = relationship("Vendor", back_populates="event_impacts")


class WeightConfig(Base):
    """
    Stores the current weight configuration for the risk engine.
    Only one active row at a time (profile_name='active').
    """
    __tablename__ = "weight_config"

    id = Column(Integer, primary_key=True, autoincrement=True)
    profile_name = Column(String(50), default="active")
    weights = Column(JSON)  # Stores dict of param->weight
    updated_at = Column(DateTime, default=datetime.utcnow)
